#!/bin/sh
# Regenerate docs/FFMPEG_COVERAGE.md from live ffmpeg/ffprobe (keeps choices in sync).
set -eu
. "$(dirname "$0")/env.sh"
OUT="$EASY_FFMPEG_ROOT/docs/FFMPEG_COVERAGE.md"
{
  echo "# FFmpeg Coverage — generated $("$FFMPEG_BIN" -version | head -1)"
  echo
  echo '> Auto-generated by `scripts/probe-ffmpeg.sh`. Do NOT hand-edit.'
  echo
  echo '## Encoders (video/audio) relevant to easy-ffmpeg codecs'
  "$FFMPEG_BIN" -encoders 2>&1 | grep -Ei ' h264| h265| hevc| av1| vp9| aac| mp3| opus| copy' || true
  echo
  echo '## Filters used by easy-ffmpeg (scale/trim/atrim)'
  "$FFMPEG_BIN" -filters 2>&1 | grep -E ' (scale|trim|atrim|fps|drawtext) ' || true
  echo
  echo '## Probe (ffprobe) JSON stream fields'
  "$FFPROBE_BIN" -h 2>&1 | grep -E 'show_streams|show_format|print_format|json' || true
} > "$OUT"
echo "[probe-ffmpeg] wrote $OUT"
